apiVersion: v1 
kind: Pod 
metadata:
  name: pod-using-nfs
spec:
  volumes:
    - name: nfs-volume 
      nfs: 
        server: 10.98.238.212 
        path: / 
  containers:
    - name: app 
      image: alpine 
      volumeMounts: 
        - name: nfs-volume
          mountPath: /var/nfs 
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/nfs/dates.txt; sleep 5; done"]